services:
  temporal-core:
    image: teastore/temporal-core
    ports:
      - 8233:8233
      - 7233:7233

  temporal-worker:
    image: teastore/temporal-worker
    depends_on:
      - temporal-core
    restart: always

  recommender-starter:
    image: teastore/recommender-starter
    depends_on:
      - temporal-core
      - temporal-worker

  inventory:
    image: teastore/inventory
    depends_on:
      - product

  product:
    image: teastore/product

  order:
    image: teastore/order

  user:
    image: teastore/user

  recommender:
    image: teastore/recommender

  image:
    image: teastore/image

  webui:
    image: teastore/webui
    depends_on:
      - temporal-core
      - temporal-worker
    ports:
      - 5000:5000


